// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"
	"zap/server/ent/predicate"
	"zap/server/ent/project"
	"zap/server/ent/projectchangelog"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeProject          = "Project"
	TypeProjectChangeLog = "ProjectChangeLog"
)

// ProjectMutation represents an operation that mutates the Project nodes in the graph.
type ProjectMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	name                 *string
	title                *string
	version              *string
	force_update         *bool
	ignore_folders       *[]string
	appendignore_folders []string
	ignore_files         *[]string
	appendignore_files   []string
	created_at           *time.Time
	is_deleted           *bool
	clearedFields        map[string]struct{}
	change_logs          map[int]struct{}
	removedchange_logs   map[int]struct{}
	clearedchange_logs   bool
	done                 bool
	oldValue             func(context.Context) (*Project, error)
	predicates           []predicate.Project
}

var _ ent.Mutation = (*ProjectMutation)(nil)

// projectOption allows management of the mutation configuration using functional options.
type projectOption func(*ProjectMutation)

// newProjectMutation creates new mutation for the Project entity.
func newProjectMutation(c config, op Op, opts ...projectOption) *ProjectMutation {
	m := &ProjectMutation{
		config:        c,
		op:            op,
		typ:           TypeProject,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProjectID sets the ID field of the mutation.
func withProjectID(id int) projectOption {
	return func(m *ProjectMutation) {
		var (
			err   error
			once  sync.Once
			value *Project
		)
		m.oldValue = func(ctx context.Context) (*Project, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Project.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProject sets the old Project of the mutation.
func withProject(node *Project) projectOption {
	return func(m *ProjectMutation) {
		m.oldValue = func(context.Context) (*Project, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProjectMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProjectMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProjectMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProjectMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Project.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ProjectMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ProjectMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ProjectMutation) ResetName() {
	m.name = nil
}

// SetTitle sets the "title" field.
func (m *ProjectMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *ProjectMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *ProjectMutation) ResetTitle() {
	m.title = nil
}

// SetVersion sets the "version" field.
func (m *ProjectMutation) SetVersion(s string) {
	m.version = &s
}

// Version returns the value of the "version" field in the mutation.
func (m *ProjectMutation) Version() (r string, exists bool) {
	v := m.version
	if v == nil {
		return
	}
	return *v, true
}

// OldVersion returns the old "version" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVersion: %w", err)
	}
	return oldValue.Version, nil
}

// ResetVersion resets all changes to the "version" field.
func (m *ProjectMutation) ResetVersion() {
	m.version = nil
}

// SetForceUpdate sets the "force_update" field.
func (m *ProjectMutation) SetForceUpdate(b bool) {
	m.force_update = &b
}

// ForceUpdate returns the value of the "force_update" field in the mutation.
func (m *ProjectMutation) ForceUpdate() (r bool, exists bool) {
	v := m.force_update
	if v == nil {
		return
	}
	return *v, true
}

// OldForceUpdate returns the old "force_update" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldForceUpdate(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldForceUpdate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldForceUpdate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldForceUpdate: %w", err)
	}
	return oldValue.ForceUpdate, nil
}

// ResetForceUpdate resets all changes to the "force_update" field.
func (m *ProjectMutation) ResetForceUpdate() {
	m.force_update = nil
}

// SetIgnoreFolders sets the "ignore_folders" field.
func (m *ProjectMutation) SetIgnoreFolders(s []string) {
	m.ignore_folders = &s
	m.appendignore_folders = nil
}

// IgnoreFolders returns the value of the "ignore_folders" field in the mutation.
func (m *ProjectMutation) IgnoreFolders() (r []string, exists bool) {
	v := m.ignore_folders
	if v == nil {
		return
	}
	return *v, true
}

// OldIgnoreFolders returns the old "ignore_folders" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldIgnoreFolders(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIgnoreFolders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIgnoreFolders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIgnoreFolders: %w", err)
	}
	return oldValue.IgnoreFolders, nil
}

// AppendIgnoreFolders adds s to the "ignore_folders" field.
func (m *ProjectMutation) AppendIgnoreFolders(s []string) {
	m.appendignore_folders = append(m.appendignore_folders, s...)
}

// AppendedIgnoreFolders returns the list of values that were appended to the "ignore_folders" field in this mutation.
func (m *ProjectMutation) AppendedIgnoreFolders() ([]string, bool) {
	if len(m.appendignore_folders) == 0 {
		return nil, false
	}
	return m.appendignore_folders, true
}

// ClearIgnoreFolders clears the value of the "ignore_folders" field.
func (m *ProjectMutation) ClearIgnoreFolders() {
	m.ignore_folders = nil
	m.appendignore_folders = nil
	m.clearedFields[project.FieldIgnoreFolders] = struct{}{}
}

// IgnoreFoldersCleared returns if the "ignore_folders" field was cleared in this mutation.
func (m *ProjectMutation) IgnoreFoldersCleared() bool {
	_, ok := m.clearedFields[project.FieldIgnoreFolders]
	return ok
}

// ResetIgnoreFolders resets all changes to the "ignore_folders" field.
func (m *ProjectMutation) ResetIgnoreFolders() {
	m.ignore_folders = nil
	m.appendignore_folders = nil
	delete(m.clearedFields, project.FieldIgnoreFolders)
}

// SetIgnoreFiles sets the "ignore_files" field.
func (m *ProjectMutation) SetIgnoreFiles(s []string) {
	m.ignore_files = &s
	m.appendignore_files = nil
}

// IgnoreFiles returns the value of the "ignore_files" field in the mutation.
func (m *ProjectMutation) IgnoreFiles() (r []string, exists bool) {
	v := m.ignore_files
	if v == nil {
		return
	}
	return *v, true
}

// OldIgnoreFiles returns the old "ignore_files" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldIgnoreFiles(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIgnoreFiles is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIgnoreFiles requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIgnoreFiles: %w", err)
	}
	return oldValue.IgnoreFiles, nil
}

// AppendIgnoreFiles adds s to the "ignore_files" field.
func (m *ProjectMutation) AppendIgnoreFiles(s []string) {
	m.appendignore_files = append(m.appendignore_files, s...)
}

// AppendedIgnoreFiles returns the list of values that were appended to the "ignore_files" field in this mutation.
func (m *ProjectMutation) AppendedIgnoreFiles() ([]string, bool) {
	if len(m.appendignore_files) == 0 {
		return nil, false
	}
	return m.appendignore_files, true
}

// ClearIgnoreFiles clears the value of the "ignore_files" field.
func (m *ProjectMutation) ClearIgnoreFiles() {
	m.ignore_files = nil
	m.appendignore_files = nil
	m.clearedFields[project.FieldIgnoreFiles] = struct{}{}
}

// IgnoreFilesCleared returns if the "ignore_files" field was cleared in this mutation.
func (m *ProjectMutation) IgnoreFilesCleared() bool {
	_, ok := m.clearedFields[project.FieldIgnoreFiles]
	return ok
}

// ResetIgnoreFiles resets all changes to the "ignore_files" field.
func (m *ProjectMutation) ResetIgnoreFiles() {
	m.ignore_files = nil
	m.appendignore_files = nil
	delete(m.clearedFields, project.FieldIgnoreFiles)
}

// SetCreatedAt sets the "created_at" field.
func (m *ProjectMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ProjectMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ProjectMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetIsDeleted sets the "is_deleted" field.
func (m *ProjectMutation) SetIsDeleted(b bool) {
	m.is_deleted = &b
}

// IsDeleted returns the value of the "is_deleted" field in the mutation.
func (m *ProjectMutation) IsDeleted() (r bool, exists bool) {
	v := m.is_deleted
	if v == nil {
		return
	}
	return *v, true
}

// OldIsDeleted returns the old "is_deleted" field's value of the Project entity.
// If the Project object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectMutation) OldIsDeleted(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsDeleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsDeleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsDeleted: %w", err)
	}
	return oldValue.IsDeleted, nil
}

// ResetIsDeleted resets all changes to the "is_deleted" field.
func (m *ProjectMutation) ResetIsDeleted() {
	m.is_deleted = nil
}

// AddChangeLogIDs adds the "change_logs" edge to the ProjectChangeLog entity by ids.
func (m *ProjectMutation) AddChangeLogIDs(ids ...int) {
	if m.change_logs == nil {
		m.change_logs = make(map[int]struct{})
	}
	for i := range ids {
		m.change_logs[ids[i]] = struct{}{}
	}
}

// ClearChangeLogs clears the "change_logs" edge to the ProjectChangeLog entity.
func (m *ProjectMutation) ClearChangeLogs() {
	m.clearedchange_logs = true
}

// ChangeLogsCleared reports if the "change_logs" edge to the ProjectChangeLog entity was cleared.
func (m *ProjectMutation) ChangeLogsCleared() bool {
	return m.clearedchange_logs
}

// RemoveChangeLogIDs removes the "change_logs" edge to the ProjectChangeLog entity by IDs.
func (m *ProjectMutation) RemoveChangeLogIDs(ids ...int) {
	if m.removedchange_logs == nil {
		m.removedchange_logs = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.change_logs, ids[i])
		m.removedchange_logs[ids[i]] = struct{}{}
	}
}

// RemovedChangeLogs returns the removed IDs of the "change_logs" edge to the ProjectChangeLog entity.
func (m *ProjectMutation) RemovedChangeLogsIDs() (ids []int) {
	for id := range m.removedchange_logs {
		ids = append(ids, id)
	}
	return
}

// ChangeLogsIDs returns the "change_logs" edge IDs in the mutation.
func (m *ProjectMutation) ChangeLogsIDs() (ids []int) {
	for id := range m.change_logs {
		ids = append(ids, id)
	}
	return
}

// ResetChangeLogs resets all changes to the "change_logs" edge.
func (m *ProjectMutation) ResetChangeLogs() {
	m.change_logs = nil
	m.clearedchange_logs = false
	m.removedchange_logs = nil
}

// Where appends a list predicates to the ProjectMutation builder.
func (m *ProjectMutation) Where(ps ...predicate.Project) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProjectMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProjectMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Project, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProjectMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProjectMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Project).
func (m *ProjectMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProjectMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.name != nil {
		fields = append(fields, project.FieldName)
	}
	if m.title != nil {
		fields = append(fields, project.FieldTitle)
	}
	if m.version != nil {
		fields = append(fields, project.FieldVersion)
	}
	if m.force_update != nil {
		fields = append(fields, project.FieldForceUpdate)
	}
	if m.ignore_folders != nil {
		fields = append(fields, project.FieldIgnoreFolders)
	}
	if m.ignore_files != nil {
		fields = append(fields, project.FieldIgnoreFiles)
	}
	if m.created_at != nil {
		fields = append(fields, project.FieldCreatedAt)
	}
	if m.is_deleted != nil {
		fields = append(fields, project.FieldIsDeleted)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProjectMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case project.FieldName:
		return m.Name()
	case project.FieldTitle:
		return m.Title()
	case project.FieldVersion:
		return m.Version()
	case project.FieldForceUpdate:
		return m.ForceUpdate()
	case project.FieldIgnoreFolders:
		return m.IgnoreFolders()
	case project.FieldIgnoreFiles:
		return m.IgnoreFiles()
	case project.FieldCreatedAt:
		return m.CreatedAt()
	case project.FieldIsDeleted:
		return m.IsDeleted()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProjectMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case project.FieldName:
		return m.OldName(ctx)
	case project.FieldTitle:
		return m.OldTitle(ctx)
	case project.FieldVersion:
		return m.OldVersion(ctx)
	case project.FieldForceUpdate:
		return m.OldForceUpdate(ctx)
	case project.FieldIgnoreFolders:
		return m.OldIgnoreFolders(ctx)
	case project.FieldIgnoreFiles:
		return m.OldIgnoreFiles(ctx)
	case project.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case project.FieldIsDeleted:
		return m.OldIsDeleted(ctx)
	}
	return nil, fmt.Errorf("unknown Project field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectMutation) SetField(name string, value ent.Value) error {
	switch name {
	case project.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case project.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case project.FieldVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVersion(v)
		return nil
	case project.FieldForceUpdate:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetForceUpdate(v)
		return nil
	case project.FieldIgnoreFolders:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIgnoreFolders(v)
		return nil
	case project.FieldIgnoreFiles:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIgnoreFiles(v)
		return nil
	case project.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case project.FieldIsDeleted:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsDeleted(v)
		return nil
	}
	return fmt.Errorf("unknown Project field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProjectMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProjectMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Project numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProjectMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(project.FieldIgnoreFolders) {
		fields = append(fields, project.FieldIgnoreFolders)
	}
	if m.FieldCleared(project.FieldIgnoreFiles) {
		fields = append(fields, project.FieldIgnoreFiles)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProjectMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProjectMutation) ClearField(name string) error {
	switch name {
	case project.FieldIgnoreFolders:
		m.ClearIgnoreFolders()
		return nil
	case project.FieldIgnoreFiles:
		m.ClearIgnoreFiles()
		return nil
	}
	return fmt.Errorf("unknown Project nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProjectMutation) ResetField(name string) error {
	switch name {
	case project.FieldName:
		m.ResetName()
		return nil
	case project.FieldTitle:
		m.ResetTitle()
		return nil
	case project.FieldVersion:
		m.ResetVersion()
		return nil
	case project.FieldForceUpdate:
		m.ResetForceUpdate()
		return nil
	case project.FieldIgnoreFolders:
		m.ResetIgnoreFolders()
		return nil
	case project.FieldIgnoreFiles:
		m.ResetIgnoreFiles()
		return nil
	case project.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case project.FieldIsDeleted:
		m.ResetIsDeleted()
		return nil
	}
	return fmt.Errorf("unknown Project field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProjectMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.change_logs != nil {
		edges = append(edges, project.EdgeChangeLogs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProjectMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case project.EdgeChangeLogs:
		ids := make([]ent.Value, 0, len(m.change_logs))
		for id := range m.change_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProjectMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedchange_logs != nil {
		edges = append(edges, project.EdgeChangeLogs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProjectMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case project.EdgeChangeLogs:
		ids := make([]ent.Value, 0, len(m.removedchange_logs))
		for id := range m.removedchange_logs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProjectMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedchange_logs {
		edges = append(edges, project.EdgeChangeLogs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProjectMutation) EdgeCleared(name string) bool {
	switch name {
	case project.EdgeChangeLogs:
		return m.clearedchange_logs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProjectMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Project unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProjectMutation) ResetEdge(name string) error {
	switch name {
	case project.EdgeChangeLogs:
		m.ResetChangeLogs()
		return nil
	}
	return fmt.Errorf("unknown Project edge %s", name)
}

// ProjectChangeLogMutation represents an operation that mutates the ProjectChangeLog nodes in the graph.
type ProjectChangeLogMutation struct {
	config
	op                        Op
	typ                       string
	id                        *int
	version                   *string
	logs                      *[]string
	appendlogs                []string
	time                      *string
	created_at                *time.Time
	is_deleted                *bool
	after_apply_update_script *string
	clearedFields             map[string]struct{}
	project                   *int
	clearedproject            bool
	done                      bool
	oldValue                  func(context.Context) (*ProjectChangeLog, error)
	predicates                []predicate.ProjectChangeLog
}

var _ ent.Mutation = (*ProjectChangeLogMutation)(nil)

// projectchangelogOption allows management of the mutation configuration using functional options.
type projectchangelogOption func(*ProjectChangeLogMutation)

// newProjectChangeLogMutation creates new mutation for the ProjectChangeLog entity.
func newProjectChangeLogMutation(c config, op Op, opts ...projectchangelogOption) *ProjectChangeLogMutation {
	m := &ProjectChangeLogMutation{
		config:        c,
		op:            op,
		typ:           TypeProjectChangeLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProjectChangeLogID sets the ID field of the mutation.
func withProjectChangeLogID(id int) projectchangelogOption {
	return func(m *ProjectChangeLogMutation) {
		var (
			err   error
			once  sync.Once
			value *ProjectChangeLog
		)
		m.oldValue = func(ctx context.Context) (*ProjectChangeLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ProjectChangeLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProjectChangeLog sets the old ProjectChangeLog of the mutation.
func withProjectChangeLog(node *ProjectChangeLog) projectchangelogOption {
	return func(m *ProjectChangeLogMutation) {
		m.oldValue = func(context.Context) (*ProjectChangeLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProjectChangeLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProjectChangeLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProjectChangeLogMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProjectChangeLogMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ProjectChangeLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetProjectID sets the "project_id" field.
func (m *ProjectChangeLogMutation) SetProjectID(i int) {
	m.project = &i
}

// ProjectID returns the value of the "project_id" field in the mutation.
func (m *ProjectChangeLogMutation) ProjectID() (r int, exists bool) {
	v := m.project
	if v == nil {
		return
	}
	return *v, true
}

// OldProjectID returns the old "project_id" field's value of the ProjectChangeLog entity.
// If the ProjectChangeLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectChangeLogMutation) OldProjectID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProjectID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProjectID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProjectID: %w", err)
	}
	return oldValue.ProjectID, nil
}

// ClearProjectID clears the value of the "project_id" field.
func (m *ProjectChangeLogMutation) ClearProjectID() {
	m.project = nil
	m.clearedFields[projectchangelog.FieldProjectID] = struct{}{}
}

// ProjectIDCleared returns if the "project_id" field was cleared in this mutation.
func (m *ProjectChangeLogMutation) ProjectIDCleared() bool {
	_, ok := m.clearedFields[projectchangelog.FieldProjectID]
	return ok
}

// ResetProjectID resets all changes to the "project_id" field.
func (m *ProjectChangeLogMutation) ResetProjectID() {
	m.project = nil
	delete(m.clearedFields, projectchangelog.FieldProjectID)
}

// SetVersion sets the "version" field.
func (m *ProjectChangeLogMutation) SetVersion(s string) {
	m.version = &s
}

// Version returns the value of the "version" field in the mutation.
func (m *ProjectChangeLogMutation) Version() (r string, exists bool) {
	v := m.version
	if v == nil {
		return
	}
	return *v, true
}

// OldVersion returns the old "version" field's value of the ProjectChangeLog entity.
// If the ProjectChangeLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectChangeLogMutation) OldVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVersion: %w", err)
	}
	return oldValue.Version, nil
}

// ResetVersion resets all changes to the "version" field.
func (m *ProjectChangeLogMutation) ResetVersion() {
	m.version = nil
}

// SetLogs sets the "logs" field.
func (m *ProjectChangeLogMutation) SetLogs(s []string) {
	m.logs = &s
	m.appendlogs = nil
}

// Logs returns the value of the "logs" field in the mutation.
func (m *ProjectChangeLogMutation) Logs() (r []string, exists bool) {
	v := m.logs
	if v == nil {
		return
	}
	return *v, true
}

// OldLogs returns the old "logs" field's value of the ProjectChangeLog entity.
// If the ProjectChangeLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectChangeLogMutation) OldLogs(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLogs is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLogs requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLogs: %w", err)
	}
	return oldValue.Logs, nil
}

// AppendLogs adds s to the "logs" field.
func (m *ProjectChangeLogMutation) AppendLogs(s []string) {
	m.appendlogs = append(m.appendlogs, s...)
}

// AppendedLogs returns the list of values that were appended to the "logs" field in this mutation.
func (m *ProjectChangeLogMutation) AppendedLogs() ([]string, bool) {
	if len(m.appendlogs) == 0 {
		return nil, false
	}
	return m.appendlogs, true
}

// ResetLogs resets all changes to the "logs" field.
func (m *ProjectChangeLogMutation) ResetLogs() {
	m.logs = nil
	m.appendlogs = nil
}

// SetTime sets the "time" field.
func (m *ProjectChangeLogMutation) SetTime(s string) {
	m.time = &s
}

// Time returns the value of the "time" field in the mutation.
func (m *ProjectChangeLogMutation) Time() (r string, exists bool) {
	v := m.time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "time" field's value of the ProjectChangeLog entity.
// If the ProjectChangeLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectChangeLogMutation) OldTime(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// ResetTime resets all changes to the "time" field.
func (m *ProjectChangeLogMutation) ResetTime() {
	m.time = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ProjectChangeLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ProjectChangeLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the ProjectChangeLog entity.
// If the ProjectChangeLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectChangeLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ProjectChangeLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetIsDeleted sets the "is_deleted" field.
func (m *ProjectChangeLogMutation) SetIsDeleted(b bool) {
	m.is_deleted = &b
}

// IsDeleted returns the value of the "is_deleted" field in the mutation.
func (m *ProjectChangeLogMutation) IsDeleted() (r bool, exists bool) {
	v := m.is_deleted
	if v == nil {
		return
	}
	return *v, true
}

// OldIsDeleted returns the old "is_deleted" field's value of the ProjectChangeLog entity.
// If the ProjectChangeLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectChangeLogMutation) OldIsDeleted(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsDeleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsDeleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsDeleted: %w", err)
	}
	return oldValue.IsDeleted, nil
}

// ResetIsDeleted resets all changes to the "is_deleted" field.
func (m *ProjectChangeLogMutation) ResetIsDeleted() {
	m.is_deleted = nil
}

// SetAfterApplyUpdateScript sets the "after_apply_update_script" field.
func (m *ProjectChangeLogMutation) SetAfterApplyUpdateScript(s string) {
	m.after_apply_update_script = &s
}

// AfterApplyUpdateScript returns the value of the "after_apply_update_script" field in the mutation.
func (m *ProjectChangeLogMutation) AfterApplyUpdateScript() (r string, exists bool) {
	v := m.after_apply_update_script
	if v == nil {
		return
	}
	return *v, true
}

// OldAfterApplyUpdateScript returns the old "after_apply_update_script" field's value of the ProjectChangeLog entity.
// If the ProjectChangeLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProjectChangeLogMutation) OldAfterApplyUpdateScript(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAfterApplyUpdateScript is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAfterApplyUpdateScript requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAfterApplyUpdateScript: %w", err)
	}
	return oldValue.AfterApplyUpdateScript, nil
}

// ClearAfterApplyUpdateScript clears the value of the "after_apply_update_script" field.
func (m *ProjectChangeLogMutation) ClearAfterApplyUpdateScript() {
	m.after_apply_update_script = nil
	m.clearedFields[projectchangelog.FieldAfterApplyUpdateScript] = struct{}{}
}

// AfterApplyUpdateScriptCleared returns if the "after_apply_update_script" field was cleared in this mutation.
func (m *ProjectChangeLogMutation) AfterApplyUpdateScriptCleared() bool {
	_, ok := m.clearedFields[projectchangelog.FieldAfterApplyUpdateScript]
	return ok
}

// ResetAfterApplyUpdateScript resets all changes to the "after_apply_update_script" field.
func (m *ProjectChangeLogMutation) ResetAfterApplyUpdateScript() {
	m.after_apply_update_script = nil
	delete(m.clearedFields, projectchangelog.FieldAfterApplyUpdateScript)
}

// ClearProject clears the "project" edge to the Project entity.
func (m *ProjectChangeLogMutation) ClearProject() {
	m.clearedproject = true
	m.clearedFields[projectchangelog.FieldProjectID] = struct{}{}
}

// ProjectCleared reports if the "project" edge to the Project entity was cleared.
func (m *ProjectChangeLogMutation) ProjectCleared() bool {
	return m.ProjectIDCleared() || m.clearedproject
}

// ProjectIDs returns the "project" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ProjectID instead. It exists only for internal usage by the builders.
func (m *ProjectChangeLogMutation) ProjectIDs() (ids []int) {
	if id := m.project; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetProject resets all changes to the "project" edge.
func (m *ProjectChangeLogMutation) ResetProject() {
	m.project = nil
	m.clearedproject = false
}

// Where appends a list predicates to the ProjectChangeLogMutation builder.
func (m *ProjectChangeLogMutation) Where(ps ...predicate.ProjectChangeLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProjectChangeLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProjectChangeLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.ProjectChangeLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProjectChangeLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProjectChangeLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (ProjectChangeLog).
func (m *ProjectChangeLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProjectChangeLogMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.project != nil {
		fields = append(fields, projectchangelog.FieldProjectID)
	}
	if m.version != nil {
		fields = append(fields, projectchangelog.FieldVersion)
	}
	if m.logs != nil {
		fields = append(fields, projectchangelog.FieldLogs)
	}
	if m.time != nil {
		fields = append(fields, projectchangelog.FieldTime)
	}
	if m.created_at != nil {
		fields = append(fields, projectchangelog.FieldCreatedAt)
	}
	if m.is_deleted != nil {
		fields = append(fields, projectchangelog.FieldIsDeleted)
	}
	if m.after_apply_update_script != nil {
		fields = append(fields, projectchangelog.FieldAfterApplyUpdateScript)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProjectChangeLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case projectchangelog.FieldProjectID:
		return m.ProjectID()
	case projectchangelog.FieldVersion:
		return m.Version()
	case projectchangelog.FieldLogs:
		return m.Logs()
	case projectchangelog.FieldTime:
		return m.Time()
	case projectchangelog.FieldCreatedAt:
		return m.CreatedAt()
	case projectchangelog.FieldIsDeleted:
		return m.IsDeleted()
	case projectchangelog.FieldAfterApplyUpdateScript:
		return m.AfterApplyUpdateScript()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProjectChangeLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case projectchangelog.FieldProjectID:
		return m.OldProjectID(ctx)
	case projectchangelog.FieldVersion:
		return m.OldVersion(ctx)
	case projectchangelog.FieldLogs:
		return m.OldLogs(ctx)
	case projectchangelog.FieldTime:
		return m.OldTime(ctx)
	case projectchangelog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case projectchangelog.FieldIsDeleted:
		return m.OldIsDeleted(ctx)
	case projectchangelog.FieldAfterApplyUpdateScript:
		return m.OldAfterApplyUpdateScript(ctx)
	}
	return nil, fmt.Errorf("unknown ProjectChangeLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectChangeLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case projectchangelog.FieldProjectID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProjectID(v)
		return nil
	case projectchangelog.FieldVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVersion(v)
		return nil
	case projectchangelog.FieldLogs:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLogs(v)
		return nil
	case projectchangelog.FieldTime:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	case projectchangelog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case projectchangelog.FieldIsDeleted:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsDeleted(v)
		return nil
	case projectchangelog.FieldAfterApplyUpdateScript:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAfterApplyUpdateScript(v)
		return nil
	}
	return fmt.Errorf("unknown ProjectChangeLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProjectChangeLogMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProjectChangeLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProjectChangeLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ProjectChangeLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProjectChangeLogMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(projectchangelog.FieldProjectID) {
		fields = append(fields, projectchangelog.FieldProjectID)
	}
	if m.FieldCleared(projectchangelog.FieldAfterApplyUpdateScript) {
		fields = append(fields, projectchangelog.FieldAfterApplyUpdateScript)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProjectChangeLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProjectChangeLogMutation) ClearField(name string) error {
	switch name {
	case projectchangelog.FieldProjectID:
		m.ClearProjectID()
		return nil
	case projectchangelog.FieldAfterApplyUpdateScript:
		m.ClearAfterApplyUpdateScript()
		return nil
	}
	return fmt.Errorf("unknown ProjectChangeLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProjectChangeLogMutation) ResetField(name string) error {
	switch name {
	case projectchangelog.FieldProjectID:
		m.ResetProjectID()
		return nil
	case projectchangelog.FieldVersion:
		m.ResetVersion()
		return nil
	case projectchangelog.FieldLogs:
		m.ResetLogs()
		return nil
	case projectchangelog.FieldTime:
		m.ResetTime()
		return nil
	case projectchangelog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case projectchangelog.FieldIsDeleted:
		m.ResetIsDeleted()
		return nil
	case projectchangelog.FieldAfterApplyUpdateScript:
		m.ResetAfterApplyUpdateScript()
		return nil
	}
	return fmt.Errorf("unknown ProjectChangeLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProjectChangeLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.project != nil {
		edges = append(edges, projectchangelog.EdgeProject)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProjectChangeLogMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case projectchangelog.EdgeProject:
		if id := m.project; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProjectChangeLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProjectChangeLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProjectChangeLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedproject {
		edges = append(edges, projectchangelog.EdgeProject)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProjectChangeLogMutation) EdgeCleared(name string) bool {
	switch name {
	case projectchangelog.EdgeProject:
		return m.clearedproject
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProjectChangeLogMutation) ClearEdge(name string) error {
	switch name {
	case projectchangelog.EdgeProject:
		m.ClearProject()
		return nil
	}
	return fmt.Errorf("unknown ProjectChangeLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProjectChangeLogMutation) ResetEdge(name string) error {
	switch name {
	case projectchangelog.EdgeProject:
		m.ResetProject()
		return nil
	}
	return fmt.Errorf("unknown ProjectChangeLog edge %s", name)
}
