// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"zap/server/ent/project"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 项目名称，用于创建文件夹保存文件，创建后不能更改
	Name string `json:"name,omitempty"`
	// 项目抬头
	Title string `json:"title,omitempty"`
	// 项目版本
	Version string `json:"version,omitempty"`
	// 是否强制更新
	ForceUpdate bool `json:"force_update,omitempty"`
	// 忽略的文件夹
	IgnoreFolders []string `json:"ignore_folders,omitempty"`
	// 忽略的文件
	IgnoreFiles []string `json:"ignore_files,omitempty"`
	// 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 是否被删除
	IsDeleted bool `json:"is_deleted,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// ChangeLogs holds the value of the change_logs edge.
	ChangeLogs []*ProjectChangeLog `json:"change_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ChangeLogsOrErr returns the ChangeLogs value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ChangeLogsOrErr() ([]*ProjectChangeLog, error) {
	if e.loadedTypes[0] {
		return e.ChangeLogs, nil
	}
	return nil, &NotLoadedError{edge: "change_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldIgnoreFolders, project.FieldIgnoreFiles:
			values[i] = new([]byte)
		case project.FieldForceUpdate, project.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case project.FieldID:
			values[i] = new(sql.NullInt64)
		case project.FieldName, project.FieldTitle, project.FieldVersion:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case project.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case project.FieldForceUpdate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field force_update", values[i])
			} else if value.Valid {
				_m.ForceUpdate = value.Bool
			}
		case project.FieldIgnoreFolders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ignore_folders", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IgnoreFolders); err != nil {
					return fmt.Errorf("unmarshal field ignore_folders: %w", err)
				}
			}
		case project.FieldIgnoreFiles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ignore_files", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IgnoreFiles); err != nil {
					return fmt.Errorf("unmarshal field ignore_files: %w", err)
				}
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				_m.IsDeleted = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChangeLogs queries the "change_logs" edge of the Project entity.
func (_m *Project) QueryChangeLogs() *ProjectChangeLogQuery {
	return NewProjectClient(_m.config).QueryChangeLogs(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("force_update=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForceUpdate))
	builder.WriteString(", ")
	builder.WriteString("ignore_folders=")
	builder.WriteString(fmt.Sprintf("%v", _m.IgnoreFolders))
	builder.WriteString(", ")
	builder.WriteString("ignore_files=")
	builder.WriteString(fmt.Sprintf("%v", _m.IgnoreFiles))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDeleted))
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
