// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"aly/server/ent/predicate"
	"aly/server/ent/project"
	"aly/server/ent/projectchangelog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProjectUpdate) SetTitle(v string) *ProjectUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableTitle(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProjectUpdate) SetVersion(v string) *ProjectUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableVersion(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetForceUpdate sets the "force_update" field.
func (_u *ProjectUpdate) SetForceUpdate(v bool) *ProjectUpdate {
	_u.mutation.SetForceUpdate(v)
	return _u
}

// SetNillableForceUpdate sets the "force_update" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableForceUpdate(v *bool) *ProjectUpdate {
	if v != nil {
		_u.SetForceUpdate(*v)
	}
	return _u
}

// SetIgnoreFolders sets the "ignore_folders" field.
func (_u *ProjectUpdate) SetIgnoreFolders(v []string) *ProjectUpdate {
	_u.mutation.SetIgnoreFolders(v)
	return _u
}

// AppendIgnoreFolders appends value to the "ignore_folders" field.
func (_u *ProjectUpdate) AppendIgnoreFolders(v []string) *ProjectUpdate {
	_u.mutation.AppendIgnoreFolders(v)
	return _u
}

// ClearIgnoreFolders clears the value of the "ignore_folders" field.
func (_u *ProjectUpdate) ClearIgnoreFolders() *ProjectUpdate {
	_u.mutation.ClearIgnoreFolders()
	return _u
}

// SetIgnoreFiles sets the "ignore_files" field.
func (_u *ProjectUpdate) SetIgnoreFiles(v []string) *ProjectUpdate {
	_u.mutation.SetIgnoreFiles(v)
	return _u
}

// AppendIgnoreFiles appends value to the "ignore_files" field.
func (_u *ProjectUpdate) AppendIgnoreFiles(v []string) *ProjectUpdate {
	_u.mutation.AppendIgnoreFiles(v)
	return _u
}

// ClearIgnoreFiles clears the value of the "ignore_files" field.
func (_u *ProjectUpdate) ClearIgnoreFiles() *ProjectUpdate {
	_u.mutation.ClearIgnoreFiles()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProjectUpdate) SetCreatedAt(v time.Time) *ProjectUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableCreatedAt(v *time.Time) *ProjectUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *ProjectUpdate) SetIsDeleted(v bool) *ProjectUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableIsDeleted(v *bool) *ProjectUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// AddChangeLogIDs adds the "change_logs" edge to the ProjectChangeLog entity by IDs.
func (_u *ProjectUpdate) AddChangeLogIDs(ids ...int) *ProjectUpdate {
	_u.mutation.AddChangeLogIDs(ids...)
	return _u
}

// AddChangeLogs adds the "change_logs" edges to the ProjectChangeLog entity.
func (_u *ProjectUpdate) AddChangeLogs(v ...*ProjectChangeLog) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeLogIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearChangeLogs clears all "change_logs" edges to the ProjectChangeLog entity.
func (_u *ProjectUpdate) ClearChangeLogs() *ProjectUpdate {
	_u.mutation.ClearChangeLogs()
	return _u
}

// RemoveChangeLogIDs removes the "change_logs" edge to ProjectChangeLog entities by IDs.
func (_u *ProjectUpdate) RemoveChangeLogIDs(ids ...int) *ProjectUpdate {
	_u.mutation.RemoveChangeLogIDs(ids...)
	return _u
}

// RemoveChangeLogs removes "change_logs" edges to ProjectChangeLog entities.
func (_u *ProjectUpdate) RemoveChangeLogs(v ...*ProjectChangeLog) *ProjectUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(project.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForceUpdate(); ok {
		_spec.SetField(project.FieldForceUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreFolders(); ok {
		_spec.SetField(project.FieldIgnoreFolders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIgnoreFolders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldIgnoreFolders, value)
		})
	}
	if _u.mutation.IgnoreFoldersCleared() {
		_spec.ClearField(project.FieldIgnoreFolders, field.TypeJSON)
	}
	if value, ok := _u.mutation.IgnoreFiles(); ok {
		_spec.SetField(project.FieldIgnoreFiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIgnoreFiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldIgnoreFiles, value)
		})
	}
	if _u.mutation.IgnoreFilesCleared() {
		_spec.ClearField(project.FieldIgnoreFiles, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(project.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(project.FieldIsDeleted, field.TypeBool, value)
	}
	if _u.mutation.ChangeLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangeLogsTable,
			Columns: []string{project.ChangeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangeLogsIDs(); len(nodes) > 0 && !_u.mutation.ChangeLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangeLogsTable,
			Columns: []string{project.ChangeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangeLogsTable,
			Columns: []string{project.ChangeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProjectUpdateOne) SetTitle(v string) *ProjectUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableTitle(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProjectUpdateOne) SetVersion(v string) *ProjectUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableVersion(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetForceUpdate sets the "force_update" field.
func (_u *ProjectUpdateOne) SetForceUpdate(v bool) *ProjectUpdateOne {
	_u.mutation.SetForceUpdate(v)
	return _u
}

// SetNillableForceUpdate sets the "force_update" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableForceUpdate(v *bool) *ProjectUpdateOne {
	if v != nil {
		_u.SetForceUpdate(*v)
	}
	return _u
}

// SetIgnoreFolders sets the "ignore_folders" field.
func (_u *ProjectUpdateOne) SetIgnoreFolders(v []string) *ProjectUpdateOne {
	_u.mutation.SetIgnoreFolders(v)
	return _u
}

// AppendIgnoreFolders appends value to the "ignore_folders" field.
func (_u *ProjectUpdateOne) AppendIgnoreFolders(v []string) *ProjectUpdateOne {
	_u.mutation.AppendIgnoreFolders(v)
	return _u
}

// ClearIgnoreFolders clears the value of the "ignore_folders" field.
func (_u *ProjectUpdateOne) ClearIgnoreFolders() *ProjectUpdateOne {
	_u.mutation.ClearIgnoreFolders()
	return _u
}

// SetIgnoreFiles sets the "ignore_files" field.
func (_u *ProjectUpdateOne) SetIgnoreFiles(v []string) *ProjectUpdateOne {
	_u.mutation.SetIgnoreFiles(v)
	return _u
}

// AppendIgnoreFiles appends value to the "ignore_files" field.
func (_u *ProjectUpdateOne) AppendIgnoreFiles(v []string) *ProjectUpdateOne {
	_u.mutation.AppendIgnoreFiles(v)
	return _u
}

// ClearIgnoreFiles clears the value of the "ignore_files" field.
func (_u *ProjectUpdateOne) ClearIgnoreFiles() *ProjectUpdateOne {
	_u.mutation.ClearIgnoreFiles()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProjectUpdateOne) SetCreatedAt(v time.Time) *ProjectUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableCreatedAt(v *time.Time) *ProjectUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *ProjectUpdateOne) SetIsDeleted(v bool) *ProjectUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableIsDeleted(v *bool) *ProjectUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// AddChangeLogIDs adds the "change_logs" edge to the ProjectChangeLog entity by IDs.
func (_u *ProjectUpdateOne) AddChangeLogIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.AddChangeLogIDs(ids...)
	return _u
}

// AddChangeLogs adds the "change_logs" edges to the ProjectChangeLog entity.
func (_u *ProjectUpdateOne) AddChangeLogs(v ...*ProjectChangeLog) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeLogIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearChangeLogs clears all "change_logs" edges to the ProjectChangeLog entity.
func (_u *ProjectUpdateOne) ClearChangeLogs() *ProjectUpdateOne {
	_u.mutation.ClearChangeLogs()
	return _u
}

// RemoveChangeLogIDs removes the "change_logs" edge to ProjectChangeLog entities by IDs.
func (_u *ProjectUpdateOne) RemoveChangeLogIDs(ids ...int) *ProjectUpdateOne {
	_u.mutation.RemoveChangeLogIDs(ids...)
	return _u
}

// RemoveChangeLogs removes "change_logs" edges to ProjectChangeLog entities.
func (_u *ProjectUpdateOne) RemoveChangeLogs(v ...*ProjectChangeLog) *ProjectUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeLogIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(project.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForceUpdate(); ok {
		_spec.SetField(project.FieldForceUpdate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IgnoreFolders(); ok {
		_spec.SetField(project.FieldIgnoreFolders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIgnoreFolders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldIgnoreFolders, value)
		})
	}
	if _u.mutation.IgnoreFoldersCleared() {
		_spec.ClearField(project.FieldIgnoreFolders, field.TypeJSON)
	}
	if value, ok := _u.mutation.IgnoreFiles(); ok {
		_spec.SetField(project.FieldIgnoreFiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIgnoreFiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldIgnoreFiles, value)
		})
	}
	if _u.mutation.IgnoreFilesCleared() {
		_spec.ClearField(project.FieldIgnoreFiles, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(project.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(project.FieldIsDeleted, field.TypeBool, value)
	}
	if _u.mutation.ChangeLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangeLogsTable,
			Columns: []string{project.ChangeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangeLogsIDs(); len(nodes) > 0 && !_u.mutation.ChangeLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangeLogsTable,
			Columns: []string{project.ChangeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangeLogsTable,
			Columns: []string{project.ChangeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
