// Code generated by ent, DO NOT EDIT.

package ent

import (
	"zap/server/ent/project"
	"zap/server/ent/projectchangelog"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProjectChangeLog is the model entity for the ProjectChangeLog schema.
type ProjectChangeLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 版本号
	Version string `json:"version,omitempty"`
	// 变更日志集合
	Logs []string `json:"logs,omitempty"`
	// 变更时间
	Time string `json:"time,omitempty"`
	// 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 是否被删除
	IsDeleted bool `json:"is_deleted,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectChangeLogQuery when eager-loading is set.
	Edges               ProjectChangeLogEdges `json:"edges"`
	project_change_logs *int
	selectValues        sql.SelectValues
}

// ProjectChangeLogEdges holds the relations/edges for other nodes in the graph.
type ProjectChangeLogEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectChangeLogEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectChangeLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectchangelog.FieldLogs:
			values[i] = new([]byte)
		case projectchangelog.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case projectchangelog.FieldID:
			values[i] = new(sql.NullInt64)
		case projectchangelog.FieldVersion, projectchangelog.FieldTime:
			values[i] = new(sql.NullString)
		case projectchangelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case projectchangelog.ForeignKeys[0]: // project_change_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectChangeLog fields.
func (_m *ProjectChangeLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectchangelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case projectchangelog.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case projectchangelog.FieldLogs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field logs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Logs); err != nil {
					return fmt.Errorf("unmarshal field logs: %w", err)
				}
			}
		case projectchangelog.FieldTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				_m.Time = value.String
			}
		case projectchangelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case projectchangelog.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				_m.IsDeleted = value.Bool
			}
		case projectchangelog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field project_change_logs", value)
			} else if value.Valid {
				_m.project_change_logs = new(int)
				*_m.project_change_logs = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectChangeLog.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectChangeLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectChangeLog entity.
func (_m *ProjectChangeLog) QueryProject() *ProjectQuery {
	return NewProjectChangeLogClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this ProjectChangeLog.
// Note that you need to call ProjectChangeLog.Unwrap() before calling this method if this ProjectChangeLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectChangeLog) Update() *ProjectChangeLogUpdateOne {
	return NewProjectChangeLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectChangeLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectChangeLog) Unwrap() *ProjectChangeLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectChangeLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectChangeLog) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectChangeLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("logs=")
	builder.WriteString(fmt.Sprintf("%v", _m.Logs))
	builder.WriteString(", ")
	builder.WriteString("time=")
	builder.WriteString(_m.Time)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDeleted))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectChangeLogs is a parsable slice of ProjectChangeLog.
type ProjectChangeLogs []*ProjectChangeLog
