// Code generated by ent, DO NOT EDIT.

package ent

import (
	"zap/server/ent/project"
	"zap/server/ent/projectchangelog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectChangeLogCreate is the builder for creating a ProjectChangeLog entity.
type ProjectChangeLogCreate struct {
	config
	mutation *ProjectChangeLogMutation
	hooks    []Hook
}

// SetVersion sets the "version" field.
func (_c *ProjectChangeLogCreate) SetVersion(v string) *ProjectChangeLogCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetLogs sets the "logs" field.
func (_c *ProjectChangeLogCreate) SetLogs(v []string) *ProjectChangeLogCreate {
	_c.mutation.SetLogs(v)
	return _c
}

// SetTime sets the "time" field.
func (_c *ProjectChangeLogCreate) SetTime(v string) *ProjectChangeLogCreate {
	_c.mutation.SetTime(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectChangeLogCreate) SetCreatedAt(v time.Time) *ProjectChangeLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectChangeLogCreate) SetNillableCreatedAt(v *time.Time) *ProjectChangeLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *ProjectChangeLogCreate) SetIsDeleted(v bool) *ProjectChangeLogCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *ProjectChangeLogCreate) SetNillableIsDeleted(v *bool) *ProjectChangeLogCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_c *ProjectChangeLogCreate) SetProjectID(id int) *ProjectChangeLogCreate {
	_c.mutation.SetProjectID(id)
	return _c
}

// SetNillableProjectID sets the "project" edge to the Project entity by ID if the given value is not nil.
func (_c *ProjectChangeLogCreate) SetNillableProjectID(id *int) *ProjectChangeLogCreate {
	if id != nil {
		_c = _c.SetProjectID(*id)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *ProjectChangeLogCreate) SetProject(v *Project) *ProjectChangeLogCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the ProjectChangeLogMutation object of the builder.
func (_c *ProjectChangeLogCreate) Mutation() *ProjectChangeLogMutation {
	return _c.mutation
}

// Save creates the ProjectChangeLog in the database.
func (_c *ProjectChangeLogCreate) Save(ctx context.Context) (*ProjectChangeLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectChangeLogCreate) SaveX(ctx context.Context) *ProjectChangeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectChangeLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectChangeLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectChangeLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := projectchangelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := projectchangelog.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectChangeLogCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ProjectChangeLog.version"`)}
	}
	if _, ok := _c.mutation.Logs(); !ok {
		return &ValidationError{Name: "logs", err: errors.New(`ent: missing required field "ProjectChangeLog.logs"`)}
	}
	if _, ok := _c.mutation.Time(); !ok {
		return &ValidationError{Name: "time", err: errors.New(`ent: missing required field "ProjectChangeLog.time"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectChangeLog.created_at"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "ProjectChangeLog.is_deleted"`)}
	}
	return nil
}

func (_c *ProjectChangeLogCreate) sqlSave(ctx context.Context) (*ProjectChangeLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectChangeLogCreate) createSpec() (*ProjectChangeLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectChangeLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(projectchangelog.Table, sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(projectchangelog.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Logs(); ok {
		_spec.SetField(projectchangelog.FieldLogs, field.TypeJSON, value)
		_node.Logs = value
	}
	if value, ok := _c.mutation.Time(); ok {
		_spec.SetField(projectchangelog.FieldTime, field.TypeString, value)
		_node.Time = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(projectchangelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(projectchangelog.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectchangelog.ProjectTable,
			Columns: []string{projectchangelog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.project_change_logs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectChangeLogCreateBulk is the builder for creating many ProjectChangeLog entities in bulk.
type ProjectChangeLogCreateBulk struct {
	config
	err      error
	builders []*ProjectChangeLogCreate
}

// Save creates the ProjectChangeLog entities in the database.
func (_c *ProjectChangeLogCreateBulk) Save(ctx context.Context) ([]*ProjectChangeLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProjectChangeLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectChangeLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectChangeLogCreateBulk) SaveX(ctx context.Context) []*ProjectChangeLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectChangeLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectChangeLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
