// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"zap/server/ent/predicate"
	"zap/server/ent/project"
	"zap/server/ent/projectchangelog"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProjectChangeLogUpdate is the builder for updating ProjectChangeLog entities.
type ProjectChangeLogUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectChangeLogMutation
}

// Where appends a list predicates to the ProjectChangeLogUpdate builder.
func (_u *ProjectChangeLogUpdate) Where(ps ...predicate.ProjectChangeLog) *ProjectChangeLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectChangeLogUpdate) SetProjectID(v int) *ProjectChangeLogUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectChangeLogUpdate) SetNillableProjectID(v *int) *ProjectChangeLogUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *ProjectChangeLogUpdate) ClearProjectID() *ProjectChangeLogUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProjectChangeLogUpdate) SetVersion(v string) *ProjectChangeLogUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProjectChangeLogUpdate) SetNillableVersion(v *string) *ProjectChangeLogUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetLogs sets the "logs" field.
func (_u *ProjectChangeLogUpdate) SetLogs(v []string) *ProjectChangeLogUpdate {
	_u.mutation.SetLogs(v)
	return _u
}

// AppendLogs appends value to the "logs" field.
func (_u *ProjectChangeLogUpdate) AppendLogs(v []string) *ProjectChangeLogUpdate {
	_u.mutation.AppendLogs(v)
	return _u
}

// SetTime sets the "time" field.
func (_u *ProjectChangeLogUpdate) SetTime(v string) *ProjectChangeLogUpdate {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *ProjectChangeLogUpdate) SetNillableTime(v *string) *ProjectChangeLogUpdate {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProjectChangeLogUpdate) SetCreatedAt(v time.Time) *ProjectChangeLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProjectChangeLogUpdate) SetNillableCreatedAt(v *time.Time) *ProjectChangeLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *ProjectChangeLogUpdate) SetIsDeleted(v bool) *ProjectChangeLogUpdate {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *ProjectChangeLogUpdate) SetNillableIsDeleted(v *bool) *ProjectChangeLogUpdate {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetAfterApplyUpdateScript sets the "after_apply_update_script" field.
func (_u *ProjectChangeLogUpdate) SetAfterApplyUpdateScript(v string) *ProjectChangeLogUpdate {
	_u.mutation.SetAfterApplyUpdateScript(v)
	return _u
}

// SetNillableAfterApplyUpdateScript sets the "after_apply_update_script" field if the given value is not nil.
func (_u *ProjectChangeLogUpdate) SetNillableAfterApplyUpdateScript(v *string) *ProjectChangeLogUpdate {
	if v != nil {
		_u.SetAfterApplyUpdateScript(*v)
	}
	return _u
}

// ClearAfterApplyUpdateScript clears the value of the "after_apply_update_script" field.
func (_u *ProjectChangeLogUpdate) ClearAfterApplyUpdateScript() *ProjectChangeLogUpdate {
	_u.mutation.ClearAfterApplyUpdateScript()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectChangeLogUpdate) SetProject(v *Project) *ProjectChangeLogUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectChangeLogMutation object of the builder.
func (_u *ProjectChangeLogUpdate) Mutation() *ProjectChangeLogMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectChangeLogUpdate) ClearProject() *ProjectChangeLogUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectChangeLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectChangeLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectChangeLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectChangeLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProjectChangeLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(projectchangelog.Table, projectchangelog.Columns, sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(projectchangelog.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(projectchangelog.FieldLogs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLogs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, projectchangelog.FieldLogs, value)
		})
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(projectchangelog.FieldTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(projectchangelog.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(projectchangelog.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AfterApplyUpdateScript(); ok {
		_spec.SetField(projectchangelog.FieldAfterApplyUpdateScript, field.TypeString, value)
	}
	if _u.mutation.AfterApplyUpdateScriptCleared() {
		_spec.ClearField(projectchangelog.FieldAfterApplyUpdateScript, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectchangelog.ProjectTable,
			Columns: []string{projectchangelog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectchangelog.ProjectTable,
			Columns: []string{projectchangelog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectchangelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectChangeLogUpdateOne is the builder for updating a single ProjectChangeLog entity.
type ProjectChangeLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectChangeLogMutation
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectChangeLogUpdateOne) SetProjectID(v int) *ProjectChangeLogUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectChangeLogUpdateOne) SetNillableProjectID(v *int) *ProjectChangeLogUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *ProjectChangeLogUpdateOne) ClearProjectID() *ProjectChangeLogUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProjectChangeLogUpdateOne) SetVersion(v string) *ProjectChangeLogUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProjectChangeLogUpdateOne) SetNillableVersion(v *string) *ProjectChangeLogUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetLogs sets the "logs" field.
func (_u *ProjectChangeLogUpdateOne) SetLogs(v []string) *ProjectChangeLogUpdateOne {
	_u.mutation.SetLogs(v)
	return _u
}

// AppendLogs appends value to the "logs" field.
func (_u *ProjectChangeLogUpdateOne) AppendLogs(v []string) *ProjectChangeLogUpdateOne {
	_u.mutation.AppendLogs(v)
	return _u
}

// SetTime sets the "time" field.
func (_u *ProjectChangeLogUpdateOne) SetTime(v string) *ProjectChangeLogUpdateOne {
	_u.mutation.SetTime(v)
	return _u
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (_u *ProjectChangeLogUpdateOne) SetNillableTime(v *string) *ProjectChangeLogUpdateOne {
	if v != nil {
		_u.SetTime(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ProjectChangeLogUpdateOne) SetCreatedAt(v time.Time) *ProjectChangeLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ProjectChangeLogUpdateOne) SetNillableCreatedAt(v *time.Time) *ProjectChangeLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetIsDeleted sets the "is_deleted" field.
func (_u *ProjectChangeLogUpdateOne) SetIsDeleted(v bool) *ProjectChangeLogUpdateOne {
	_u.mutation.SetIsDeleted(v)
	return _u
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_u *ProjectChangeLogUpdateOne) SetNillableIsDeleted(v *bool) *ProjectChangeLogUpdateOne {
	if v != nil {
		_u.SetIsDeleted(*v)
	}
	return _u
}

// SetAfterApplyUpdateScript sets the "after_apply_update_script" field.
func (_u *ProjectChangeLogUpdateOne) SetAfterApplyUpdateScript(v string) *ProjectChangeLogUpdateOne {
	_u.mutation.SetAfterApplyUpdateScript(v)
	return _u
}

// SetNillableAfterApplyUpdateScript sets the "after_apply_update_script" field if the given value is not nil.
func (_u *ProjectChangeLogUpdateOne) SetNillableAfterApplyUpdateScript(v *string) *ProjectChangeLogUpdateOne {
	if v != nil {
		_u.SetAfterApplyUpdateScript(*v)
	}
	return _u
}

// ClearAfterApplyUpdateScript clears the value of the "after_apply_update_script" field.
func (_u *ProjectChangeLogUpdateOne) ClearAfterApplyUpdateScript() *ProjectChangeLogUpdateOne {
	_u.mutation.ClearAfterApplyUpdateScript()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectChangeLogUpdateOne) SetProject(v *Project) *ProjectChangeLogUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectChangeLogMutation object of the builder.
func (_u *ProjectChangeLogUpdateOne) Mutation() *ProjectChangeLogMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectChangeLogUpdateOne) ClearProject() *ProjectChangeLogUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ProjectChangeLogUpdate builder.
func (_u *ProjectChangeLogUpdateOne) Where(ps ...predicate.ProjectChangeLog) *ProjectChangeLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectChangeLogUpdateOne) Select(field string, fields ...string) *ProjectChangeLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectChangeLog entity.
func (_u *ProjectChangeLogUpdateOne) Save(ctx context.Context) (*ProjectChangeLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectChangeLogUpdateOne) SaveX(ctx context.Context) *ProjectChangeLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectChangeLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectChangeLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProjectChangeLogUpdateOne) sqlSave(ctx context.Context) (_node *ProjectChangeLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(projectchangelog.Table, projectchangelog.Columns, sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectChangeLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectchangelog.FieldID)
		for _, f := range fields {
			if !projectchangelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectchangelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(projectchangelog.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(projectchangelog.FieldLogs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLogs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, projectchangelog.FieldLogs, value)
		})
	}
	if value, ok := _u.mutation.Time(); ok {
		_spec.SetField(projectchangelog.FieldTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(projectchangelog.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDeleted(); ok {
		_spec.SetField(projectchangelog.FieldIsDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AfterApplyUpdateScript(); ok {
		_spec.SetField(projectchangelog.FieldAfterApplyUpdateScript, field.TypeString, value)
	}
	if _u.mutation.AfterApplyUpdateScriptCleared() {
		_spec.ClearField(projectchangelog.FieldAfterApplyUpdateScript, field.TypeString)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectchangelog.ProjectTable,
			Columns: []string{projectchangelog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectchangelog.ProjectTable,
			Columns: []string{projectchangelog.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectChangeLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectchangelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
