// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"zap/server/ent/project"
	"zap/server/ent/projectchangelog"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ProjectCreate) SetName(v string) *ProjectCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ProjectCreate) SetTitle(v string) *ProjectCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ProjectCreate) SetVersion(v string) *ProjectCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetForceUpdate sets the "force_update" field.
func (_c *ProjectCreate) SetForceUpdate(v bool) *ProjectCreate {
	_c.mutation.SetForceUpdate(v)
	return _c
}

// SetIgnoreFolders sets the "ignore_folders" field.
func (_c *ProjectCreate) SetIgnoreFolders(v []string) *ProjectCreate {
	_c.mutation.SetIgnoreFolders(v)
	return _c
}

// SetIgnoreFiles sets the "ignore_files" field.
func (_c *ProjectCreate) SetIgnoreFiles(v []string) *ProjectCreate {
	_c.mutation.SetIgnoreFiles(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectCreate) SetCreatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableCreatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetIsDeleted sets the "is_deleted" field.
func (_c *ProjectCreate) SetIsDeleted(v bool) *ProjectCreate {
	_c.mutation.SetIsDeleted(v)
	return _c
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableIsDeleted(v *bool) *ProjectCreate {
	if v != nil {
		_c.SetIsDeleted(*v)
	}
	return _c
}

// AddChangeLogIDs adds the "change_logs" edge to the ProjectChangeLog entity by IDs.
func (_c *ProjectCreate) AddChangeLogIDs(ids ...int) *ProjectCreate {
	_c.mutation.AddChangeLogIDs(ids...)
	return _c
}

// AddChangeLogs adds the "change_logs" edges to the ProjectChangeLog entity.
func (_c *ProjectCreate) AddChangeLogs(v ...*ProjectChangeLog) *ProjectCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChangeLogIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_c *ProjectCreate) Mutation() *ProjectMutation {
	return _c.mutation
}

// Save creates the Project in the database.
func (_c *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := project.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		v := project.DefaultIsDeleted
		_c.mutation.SetIsDeleted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Project.name"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Project.title"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Project.version"`)}
	}
	if _, ok := _c.mutation.ForceUpdate(); !ok {
		return &ValidationError{Name: "force_update", err: errors.New(`ent: missing required field "Project.force_update"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Project.created_at"`)}
	}
	if _, ok := _c.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "Project.is_deleted"`)}
	}
	return nil
}

func (_c *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(project.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ForceUpdate(); ok {
		_spec.SetField(project.FieldForceUpdate, field.TypeBool, value)
		_node.ForceUpdate = value
	}
	if value, ok := _c.mutation.IgnoreFolders(); ok {
		_spec.SetField(project.FieldIgnoreFolders, field.TypeJSON, value)
		_node.IgnoreFolders = value
	}
	if value, ok := _c.mutation.IgnoreFiles(); ok {
		_spec.SetField(project.FieldIgnoreFiles, field.TypeJSON, value)
		_node.IgnoreFiles = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(project.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.IsDeleted(); ok {
		_spec.SetField(project.FieldIsDeleted, field.TypeBool, value)
		_node.IsDeleted = value
	}
	if nodes := _c.mutation.ChangeLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.ChangeLogsTable,
			Columns: []string{project.ChangeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectchangelog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
}

// Save creates the Project entities in the database.
func (_c *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Project, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
