// Code generated by ent, DO NOT EDIT.

package projectchangelog

import (
	"time"
	"zap/server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLTE(FieldID, id))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldVersion, v))
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldTime, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldIsDeleted, v))
}

// AfterApplyUpdateScript applies equality check predicate on the "after_apply_update_script" field. It's identical to AfterApplyUpdateScriptEQ.
func AfterApplyUpdateScript(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldAfterApplyUpdateScript, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldContainsFold(FieldVersion, v))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLTE(FieldTime, v))
}

// TimeContains applies the Contains predicate on the "time" field.
func TimeContains(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldContains(FieldTime, v))
}

// TimeHasPrefix applies the HasPrefix predicate on the "time" field.
func TimeHasPrefix(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldHasPrefix(FieldTime, v))
}

// TimeHasSuffix applies the HasSuffix predicate on the "time" field.
func TimeHasSuffix(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldHasSuffix(FieldTime, v))
}

// TimeEqualFold applies the EqualFold predicate on the "time" field.
func TimeEqualFold(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEqualFold(FieldTime, v))
}

// TimeContainsFold applies the ContainsFold predicate on the "time" field.
func TimeContainsFold(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldContainsFold(FieldTime, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLTE(FieldCreatedAt, v))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNEQ(FieldIsDeleted, v))
}

// AfterApplyUpdateScriptEQ applies the EQ predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptEQ(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEQ(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptNEQ applies the NEQ predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptNEQ(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNEQ(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptIn applies the In predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptIn(vs ...string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldIn(FieldAfterApplyUpdateScript, vs...))
}

// AfterApplyUpdateScriptNotIn applies the NotIn predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptNotIn(vs ...string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNotIn(FieldAfterApplyUpdateScript, vs...))
}

// AfterApplyUpdateScriptGT applies the GT predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptGT(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGT(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptGTE applies the GTE predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptGTE(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldGTE(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptLT applies the LT predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptLT(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLT(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptLTE applies the LTE predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptLTE(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldLTE(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptContains applies the Contains predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptContains(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldContains(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptHasPrefix applies the HasPrefix predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptHasPrefix(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldHasPrefix(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptHasSuffix applies the HasSuffix predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptHasSuffix(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldHasSuffix(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptIsNil applies the IsNil predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptIsNil() predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldIsNull(FieldAfterApplyUpdateScript))
}

// AfterApplyUpdateScriptNotNil applies the NotNil predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptNotNil() predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldNotNull(FieldAfterApplyUpdateScript))
}

// AfterApplyUpdateScriptEqualFold applies the EqualFold predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptEqualFold(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldEqualFold(FieldAfterApplyUpdateScript, v))
}

// AfterApplyUpdateScriptContainsFold applies the ContainsFold predicate on the "after_apply_update_script" field.
func AfterApplyUpdateScriptContainsFold(v string) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.FieldContainsFold(FieldAfterApplyUpdateScript, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectChangeLog) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectChangeLog) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectChangeLog) predicate.ProjectChangeLog {
	return predicate.ProjectChangeLog(sql.NotPredicates(p))
}
