// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "force_update", Type: field.TypeBool},
		{Name: "ignore_folders", Type: field.TypeJSON, Nullable: true},
		{Name: "ignore_files", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// ProjectChangeLogsColumns holds the columns for the "project_change_logs" table.
	ProjectChangeLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeString},
		{Name: "logs", Type: field.TypeJSON},
		{Name: "time", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "after_apply_update_script", Type: field.TypeString, Nullable: true},
		{Name: "project_change_logs", Type: field.TypeInt, Nullable: true},
	}
	// ProjectChangeLogsTable holds the schema information for the "project_change_logs" table.
	ProjectChangeLogsTable = &schema.Table{
		Name:       "project_change_logs",
		Columns:    ProjectChangeLogsColumns,
		PrimaryKey: []*schema.Column{ProjectChangeLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_change_logs_projects_change_logs",
				Columns:    []*schema.Column{ProjectChangeLogsColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectsTable,
		ProjectChangeLogsTable,
	}
)

func init() {
	ProjectChangeLogsTable.ForeignKeys[0].RefTable = ProjectsTable
}
