// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldForceUpdate holds the string denoting the force_update field in the database.
	FieldForceUpdate = "force_update"
	// FieldIgnoreFolders holds the string denoting the ignore_folders field in the database.
	FieldIgnoreFolders = "ignore_folders"
	// FieldIgnoreFiles holds the string denoting the ignore_files field in the database.
	FieldIgnoreFiles = "ignore_files"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// EdgeChangeLogs holds the string denoting the change_logs edge name in mutations.
	EdgeChangeLogs = "change_logs"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// ChangeLogsTable is the table that holds the change_logs relation/edge.
	ChangeLogsTable = "project_change_logs"
	// ChangeLogsInverseTable is the table name for the ProjectChangeLog entity.
	// It exists in this package in order to avoid circular dependency with the "projectchangelog" package.
	ChangeLogsInverseTable = "project_change_logs"
	// ChangeLogsColumn is the table column denoting the change_logs relation/edge.
	ChangeLogsColumn = "project_id"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTitle,
	FieldVersion,
	FieldForceUpdate,
	FieldIgnoreFolders,
	FieldIgnoreFiles,
	FieldCreatedAt,
	FieldIsDeleted,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted bool
)

// OrderOption defines the ordering options for the Project queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByForceUpdate orders the results by the force_update field.
func ByForceUpdate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForceUpdate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByIsDeleted orders the results by the is_deleted field.
func ByIsDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDeleted, opts...).ToFunc()
}

// ByChangeLogsCount orders the results by change_logs count.
func ByChangeLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChangeLogsStep(), opts...)
	}
}

// ByChangeLogs orders the results by change_logs terms.
func ByChangeLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChangeLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChangeLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChangeLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChangeLogsTable, ChangeLogsColumn),
	)
}
